[workspace]
allow_dirty = true
changelog_update = false
dependencies_update = true
pr_branch_prefix = "release-plz-"

[[package]]
name = "baker"
changelog_update = true
git_release_enable = true
semver_check = true
publish = false

[changelog]
protect_breaking_commits = true
